version: '3'
services:

  # TODO: proxy
  # https://github.com/JonasAlfredsson/docker-nginx-certbot/

  api:
    restart: always
    container_name: occi-rest-api
    build: .
    command: uvicorn main:app --app-dir=/occi --host 0.0.0.0
    env_file:
      - ./.env 
    ports:
      - "8090:8000" # same as local dev server for now
    volumes:
      - .:/occi

  rmq:
      restart: always
      container_name: occi-rmq
      image: rabbitmq:3-management
      env_file: # set variables in .env file: RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS
        - ./.env
      ports:
        - "5672:5672" # main
        - "15672:15672" # dashboard
        

  cqworker:
     restart: always
     container_name: cq-worker
     build: .
     command: celery -A occilib.cqworker.celery worker --loglevel=info
     volumes:
        - ./archiyou-compute-worker:/compute-worker
     depends_on:
       - rmq
     volumes:
       - .:/occi

  # TODO: ayworker in node
