version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest # see: https://github.com/JonasAlfredsson/docker-nginx-certbot
    container_name: occi-nginx-certbot
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/user_conf.d/nginx.conf

  api:
    restart: always
    container_name: occi-rest-api
    build: .
    command: uvicorn main:app --app-dir=/occi --host 0.0.0.0
    env_file:
      - ./.env 
    ports:
      - "8090" # same as local dev server for now
    volumes:
      - .:/occi
    depends_on:
      - rmq
      - redis 
      - cqworker

  rmq:
      restart: always
      container_name: occi-rmq
      image: rabbitmq:3-management
      env_file: # set variables in .env file: RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS
        - ./.env
      ports:
        - "5672" # main
        - "15672" # dashboard

  redis:
      image: redis:7-alpine
      container_name: occi-redis
      ports: 
        - "6379" # TODO: close after DEBUG
        

  cqworker:
    restart: always
    container_name: cq-worker
    build: .
    command: celery -A occilib.cqworker.celery worker --loglevel=info # -Q cadquery 
    volumes: # remove this to load scripts into the image on build
      - .:/occi
    depends_on:
      - rmq
      - redis 

  # TODO: ayworker in node


volumes:
  nginx_secrets: