version: '3'
services:

  # TODO: proxy
  # https://github.com/JonasAlfredsson/docker-nginx-certbot/

  api:
    restart: always
    container_name: occi-rest-api
    command: uvicorn main:app --app-dir=/occi --host 0.0.0.0
    build: .
    env_file:
      - ./.env 
    ports:
      - "8080:8000"
    volumes:
      - .:/occi

  rmq:
      restart: always
      container_name: occi-rmq
      image: rabbitmq:3-management
      env_file: # set variables in .env file: RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS
        - ./.env
      ports:
        - "15672:15672"
        - "5672:5672"

  #ayworker:
  #   restart: always
  #   container_name: ay-worker
  #   image: node:15-alpine
  #   volumes:
  #      - ./archiyou-compute-worker:/compute-worker
  #   working_dir: /compute-worker
  #   command: node --experimental-specifier-resolution=node ./build/index.js
  #   depends_on:
  #     - rmq

  # TODO: cqworker
